language: node_js

node_js:
  - "14"

notifications:
  email: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: bassages-github
    token:
      secure: "XWadQbDwQMA/dilMy6xdlgvrs4jymWJGNtd1NGfSzCvqTZTkSTX5tCb+zDJme0j1WI/AGflQgM+bAgSvs97+Y0osrouanVc/tI3TBI0ysP0hOIfG1r934mlAydgiXOQlrsSmP0TmpwCy5sSxFJM4UgqyyQMrZKmXF1fAJKpWncx6if8Bv2JcX9eIogOEajH9xh3mtTMFryxZgu3f3Bp1u/0LHrhtMTMWOR63liJ+bxOoxHxWFADkVWBaquwvV9tiPeI2qLmiBCgntkUEH2V70k7yORBuwLOZmDyxQIsmqWhUyYZgP7zv01AVjHfckjkEr8fMpoFzTmJ7CghlOSP4hhvZ4M/d7t9+d6gpW+wwpIqn3miB3fxKetrvBF2V15yNCMNKbH193w56Ywc3V4B/YpIhep9gk8FJ0NICaL4ZfJJGWmR604Zw9sTdtXSZSLemZfHirU9yU1Gwyg+anyVH16UFOwDH7bUnloXO7ahI3I3oqL5LkSb2UqnvQOUeD+lcEhh4z/yANtg97h3dPEnqwhMl48hy3mvL5ITV49J5SlQ8rao0jUdsVtMKYs3zKNDdqlf1XmnXi/jmHAcNNKQN6OdCKq7eIqYrGJAwhI2+Uwk9ENOQkmQ4YFbPXZVq0W48Esp3nCvFf2bq5/iaegAzhIAoYXAniH5BnRmDYIxK7n0="

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: n/3pQEM0nIC7/nFB0rzm4OEmnThQGhk8eQUJnkjbblrSMXbeSA1MuW0FaNWI3yO5figGlKy0H28aV2W15D2Sf7pX+qvkZ66yc/LCADmCIYcPA5yryH5OUoAWygmIppjq6m/+2IBKhm6/PAocTFvuReHuSoHrY3/1HWd6zJc34a+ASx5AI9QZfYooSpAnYkr93CmNYh+Npk773m7g76Utch+SqXriUYOQg9ussZBti7CWI4FxItDZ84d75B+kFTK9i/493cs8itgzcgvHtEisooa81pdqfk/ksPGlwlpLJh1RvLYNuBR3DhqvUfwV/A9R9+KiRl5xQ9exmUBAH9R2KbgzLQPbAMF6aF0fBRl4fK8CG17ZirnoYftnqYmC0Y65iKhBa7YRttNP4icS05qPfb77XbtjcdOISJnCFo6ddCr1X/4qmOziVvo6awbshRga3wg4WZX38xCcaqqS44lMk3HAyKDynWpXVHDQEaIDJZQeH/7oN6QTiD2NYJ7YpSN+n8QmzHWa/NAlLH4bxFF85dqkyo4Z4W82xtrhPT0GcyuTQRZfT2aoVITE6PW/jrV7stqlK/DH8MEudgRmi/h8MbSJgmff0MSHQn0mBh3fF+BdZLK5p0ukIbdWtmEnNtEiOAl2GXQwMZoopkyRXEr8vXgDz+IKNK/sL5Lny4N2vdE=
  file: dist/home-frontend.zip
  on:
    repo: bassages/home-frontend
    tags: true

