on:
  release:
    types: [published]
name: Add artifacts to release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: hmarr/debug-action@v1.0.0

      - name: Branch name
        run: echo "Release event GITHUB_REF = ${GITHUB_REF}"

      name: echo var
        run: |
          echo version name is: ${{ github.event.release.tag_name }}
          echo release title is: ${{ github.event.release.name }}
          echo release body is: ${{ github.event.release.body }}
          echo repository is: ${{ github.repository }}
