on:
  release:
    types: [published]

name: Add artifacts to release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo (debug) action details
        uses: hmarr/debug-action@v1.0.0

      - name: Checkout the tag of the release
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run npm install and npm run build
        run: |
          npm i
          npm run release-ci

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/home-frontend.zip
          asset_name: home-frontend.zip
          asset_content_type: application/zip
