on:
  release:
    types: [published]
name: Add artifacts to release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: hmarr/debug-action@v1.0.0

      - name: Branch name
        run: echo "Release event GITHUB_REF = ${GITHUB_REF}"
